name: 05 - License Compliance

on:
  workflow_dispatch:
  workflow_call:

jobs:
  license-compliance:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [front-end_PIS6TO-db594e860f4b1fa1f199237b67f00011c9d31bc0, back-end_PIS6TO-291358e1d35195c74d4328034fd56025d9795ac5]

    steps:
      - uses: actions/checkout@v4

      - uses: jmservera/license-finder-action@main
        with:
          project-path: ${{ matrix.project }}
          permitted-licenses: |
            MIT
            Apache-2.0

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: license-report-${{ matrix.project }}
          path: ${{ matrix.project }}/license_finder_report.xml

